name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cài thư viện
        run: |
          pip install ttkbootstrap minecraft-launcher-lib requests pillow pypresence pyinstaller

      - name: Build exe
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "ArchLaucher" --add-data "img;img" arch_client.py

      - uses: actions/upload-artifact@v4
        with:
          name: ArchLaucher
          path: dist/ArchLaucher.exe
